name: recomiendalo
description: Aplicación Flutter Recomiéndalo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Iconos de Cupertino
  cupertino_icons: ^1.0.8

  # Navegación
  go_router: ^16.2.1

  # Responsive
  flutter_screenutil: ^5.9.3

  flutter_riverpod: ^3.0.0

  # Íconos SVG
  flutter_svg: ^2.2.1

  # Manejo de imágenes
  image_picker: ^1.2.0

  # Drop Down
  dropdown_button2: ^2.3.9

  # Dio para peticiones HTTP
  dio: ^5.9.0

  # Dio para peticiones HTTP
  flutter_dotenv: ^6.0.0

  # selector de país con su bandera y código
  intl_phone_field: ^3.2.0

  # Fuentes de google
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/workers_without_background.png
    - assets/images/register.png
    - assets/images/otp.png
    - assets/images/security.png
    # - assets/icons/
